In [9]:
import requests
import pandas as pd
import os 
os.getcwd()

'/Users/marekerben/Desktop/IES/Midterm'

In [7]:
url = 'https://ies-python-midterm.s3.eu-central-1.amazonaws.com/studentsSets/63913338.zip'
filename = url.split('/')[-1]

r = requests.get(url) 
if r.ok:
    url_content = r.content
with open(filename, 'wb') as f:
    content = f.write(url_content)

63913338.zip

In [8]:
df1 = pd.read_csv('filename', compression = 'zip')
df1

FileNotFoundError: [Errno 2] No such file or directory: 'filename'

In [66]:
df2 = pd.read_csv('https://ies-python-midterm.s3.eu-central-1.amazonaws.com/companies/companies_no_subindustry.csv')
df2

,Symbol,Security,GICS Sector,hq,included,Founded
0,MMM,3M,Industrials,"Saint Paul, Minnesota",09.08.1976,1902
1,AOS,A. O. Smith,Industrials,"Milwaukee, Wisconsin",26.07.2017,1916
2,ABT,Abbott,Health Care,"North Chicago, Illinois",31.03.1964,1888
3,ABBV,AbbVie,Health Care,"North Chicago, Illinois",31.12.2012,2013 (1888)
4,ABMD,Abiomed,Health Care,"Danvers, Massachusetts",31.05.2018,1981
...,...,...,...,...,...,...
498,YUM,Yum! Brands,Consumer Discretionary,"Louisville, Kentucky",06.10.1997,1997
499,ZBRA,Zebra Technologies,Information Technology,"Lincolnshire, Illinois",23.12.2019,1969
500,ZBH,Zimmer Biomet,Health Care,"Warsaw, Indiana",07.08.2001,1927
501,ZION,Zions Bancorporation,Financials,"Salt Lake City, Utah",22.06.2001,1873
502,ZTS,Zoetis,Health Care,"Parsippany, New Jersey",21.06.2013,1952

In [67]:
#1
not_included = df2.included.isnull().sum()
print(f'{not_included} companies have no filled in the date of inclusion.')

45 companies have no filled in the date of inclusion.

In [68]:
df2 = df2[df2.included.notnull()].copy()
df2

,Symbol,Security,GICS Sector,hq,included,Founded
0,MMM,3M,Industrials,"Saint Paul, Minnesota",09.08.1976,1902
1,AOS,A. O. Smith,Industrials,"Milwaukee, Wisconsin",26.07.2017,1916
2,ABT,Abbott,Health Care,"North Chicago, Illinois",31.03.1964,1888
3,ABBV,AbbVie,Health Care,"North Chicago, Illinois",31.12.2012,2013 (1888)
4,ABMD,Abiomed,Health Care,"Danvers, Massachusetts",31.05.2018,1981
...,...,...,...,...,...,...
498,YUM,Yum! Brands,Consumer Discretionary,"Louisville, Kentucky",06.10.1997,1997
499,ZBRA,Zebra Technologies,Information Technology,"Lincolnshire, Illinois",23.12.2019,1969
500,ZBH,Zimmer Biomet,Health Care,"Warsaw, Indiana",07.08.2001,1927
501,ZION,Zions Bancorporation,Financials,"Salt Lake City, Utah",22.06.2001,1873
502,ZTS,Zoetis,Health Care,"Parsippany, New Jersey",21.06.2013,1952

In [69]:
df2.included = pd.to_datetime(df2.included, dayfirst=True,errors='coerce')
df2[df2.included == df2.included.min()]

,Symbol,Security,GICS Sector,hq,included,Founded
25,MO,Altria,Consumer Staples,"Richmond, Virginia",1957-03-04,1985
31,AEP,American Electric Power,Utilities,"Columbus, Ohio",1957-03-04,1906
72,BA,Boeing,Industrials,"Chicago, Illinois",1957-03-04,1916
77,BMY,Bristol Myers Squibb,Health Care,"New York City, New York",1957-03-04,1989
86,CPB,Campbell Soup Company,Consumer Staples,"Camden, New Jersey",1957-03-04,1869
93,CAT,Caterpillar Inc.,Industrials,"Irving, Texas",1957-03-04,1925
105,CVX,Chevron Corporation,Energy,"San Ramon, California",1957-03-04,1879
118,KO,The Coca-Cola Company,Consumer Staples,"Atlanta, Georgia",1957-03-04,1886
120,CL,Colgate-Palmolive,Consumer Staples,"New York City, New York",1957-03-04,1806
124,COP,ConocoPhillips,Energy,"Houston, Texas",1957-03-04,2002
138,CVS,CVS Health,Health Care,"Woonsocket, Rhode Island",1957-03-04,1996
143,DE,John Deere,Industrials,"Moline, Illinois",1957-03-04,1837
159,DTE,DTE Energy,Utilities,"Detroit, Michigan",1957-03-04,1995
167,EIX,Edison International,Utilities,"Rosemead, California",1957-03-04,1886
174,ETR,Entergy,Utilities,"New Orleans, Louisiana",1957-03-04,1913
187,EXC,Exelon,Utilities,"Chicago, Illinois",1957-03-04,2000
191,XOM,ExxonMobil,Energy,"Irving, Texas",1957-03-04,1999
204,F,Ford Motor Company,Consumer Discretionary,"Dearborn, Michigan",1957-03-04,1903
216,GD,General Dynamics,Industrials,"Falls Church, Virginia",1957-03-04,1899
225,HAL,Halliburton,Energy,"Houston, Texas",1957-03-04,1919
226,HIG,Hartford (The),Financials,"Hartford, Connecticut",1957-03-04,1810
231,HSY,Hershey's,Consumer Staples,"Hershey, Pennsylvania",1957-03-04,1894
245,IBM,IBM,Information Technology,"Armonk, New York",1957-03-04,1911
254,IP,International Paper,Materials,"Memphis, Tennessee",1957-03-04,1898
274,KMB,Kimberly-Clark,Consumer Staples,"Irving, Texas",1957-03-04,1872
279,KR,Kroger,Consumer Staples,"Cincinnati, Ohio",1957-03-04,1883
310,MRK,Merck & Co.,Health Care,"Kenilworth, New Jersey",1957-03-04,1891
342,NSC,Norfolk Southern Railway,Industrials,"Norfolk, Virginia",1957-03-04,1881/1894 (1980)
368,PEP,PepsiCo,Consumer Staples,"Purchase, New York",1957-03-04,1898
370,PFE,Pfizer,Health Care,"New York City, New York",1957-03-04,1849
378,PPG,PPG Industries,Materials,"Pittsburgh, Pennsylvania",1957-03-04,1883
381,PG,Procter & Gamble,Consumer Staples,"Cincinnati, Ohio",1957-03-04,1837
385,PEG,Public Service Enterprise Group,Utilities,"Newark, New Jersey",1957-03-04,1903
413,SEE,Sealed Air,Materials,"Charlotte, North Carolina",1957-03-04,1960
423,SO,Southern Company,Utilities,"Atlanta, Georgia",1957-03-04,1945
460,UNP,Union Pacific Corporation,Industrials,"Omaha, Nebraska",1957-03-04,1862
496,XEL,Xcel Energy,Utilities,"Minneapolis, Minnesota",1957-03-04,1909

In [70]:
df2[df2.included == df2.included.max()]

,Symbol,Security,GICS Sector,hq,included,Founded
48,ACGL,Arch Capital Group,Financials,"Hamilton, Bermuda",2022-11-01,1995

In [86]:
years_included = [2023 - i.date().year for i in df2.included]
add = 0
for i in years_included:
    add = add + i

mean = add / len(years_included)
print(f'{mean} is the average age of constituent in a sample.')

nan is the average age of constituent in a sample.

In [85]:
len(years_included)

458

In [89]:
df2.groupby(df2[2])

KeyError: 2